{% set name = "jupyterlab-snippets" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea8ed161770d72953a9e47ff373f863ddd50370071db0b1bb791673a0c40a523

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
    - jupyter-packaging >=0.7.9,<0.8
  run:
    - python >=3.6
    - jupyterlab >=3,<4

test:
  commands:
     python -c "import importlib;importlib.import_module('jupyterlab-snippets')"

about:
  home: https://github.com/QuantStack/jupyterlab-snippets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Snippets Extension for JupyterLab

  description: |
    Snippets Extension for JupyterLab

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - jtpio
